// <auto-generated />
using System;
using DeliveryCadastro.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeliveryCadastro.Migrations
{
    [DbContext(typeof(CadastroDbContext))]
    partial class CadastroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeliveryCadastro.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SENHA");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.ToTable("USUARIOS", (string)null);
                });

            modelBuilder.Entity("DeliveryCadastro.Entities.Usuario", b =>
                {
                    b.OwnsOne("DeliveryCadastro.Entities.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Bairro")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("BAIRRO");

                            b1.Property<string>("Cep")
                                .HasColumnType("varchar(9)")
                                .HasColumnName("CEP");

                            b1.Property<string>("Complemento")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("COMPLEMENTO");

                            b1.Property<string>("Municipio")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("MUNICIPIO");

                            b1.Property<int?>("Numero")
                                .HasColumnType("int")
                                .HasColumnName("NUMERO");

                            b1.Property<string>("Rua")
                                .HasColumnType("varchar(150)")
                                .HasColumnName("RUA");

                            b1.Property<string>("Uf")
                                .HasColumnType("varchar(2)")
                                .HasColumnName("UF");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("ENDERECO_USUARIO", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Endereco");
                });
#pragma warning restore 612, 618
        }
    }
}
